-- phpMyAdmin SQL Dump
-- version 4.0.10.7
-- http://www.phpmyadmin.net
--
-- Servidor: 127.13.30.2:3306
-- Tiempo de generación: 13-02-2015 a las 08:08:25
-- Versión del servidor: 5.5.41
-- Versión de PHP: 5.3.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de datos: `kelo`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `vinedo`
--

CREATE TABLE IF NOT EXISTS `vinedo` (
  `imagen` varchar(5000) NOT NULL,
  `infor` varchar(5000) NOT NULL,
  `informacion` varchar(5000) NOT NULL,
  `provincia` varchar(50) NOT NULL,
  `nombre` varchar(100) NOT NULL,
  `telefono` varchar(30) NOT NULL,
  `direccion` varchar(100) NOT NULL,
  `gmail` varchar(150) NOT NULL,
  `tinto` varchar(1000) NOT NULL,
  `rosado` varchar(1000) NOT NULL,
  `blanco` varchar(1000) NOT NULL,
  `busqueda` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Truncar tablas antes de insertar `vinedo`
--

TRUNCATE TABLE `vinedo`;
--
-- Volcado de datos para la tabla `vinedo`
--

INSERT INTO `vinedo` (`imagen`, `infor`, `informacion`, `provincia`, `nombre`, `telefono`, `direccion`, `gmail`, `tinto`, `rosado`, `blanco`, `busqueda`) VALUES
('https://www.mediafire.com/convkey/b0a9/ox55tan3f38r89w6g.jpg', 'Bodegas y Viñedos Artuke es una pequeña, coqueta e impecable instalación donde una familia con arraigada tradición vitivinícola elabora vino de las uvas de sus propios viñedos.', 'Bodegas y Viñedos Artuke es una pequeña, coqueta e impecable instalación donde una familia con arraigada tradición vitivinícola \r\nelabora vino de las uvas de sus propios viñedos. Fue en el año 1985 cuando iniciaron su nueva andadura con la inauguración de \r\nsus instalaciones en el actual enclave, en la zona sur del pueblo.Roberto Miguel Blanco, fundador de la bodega, desde muy joven\r\ndecide continuar el camino de sus antepasados', 'Alava', 'Artuke', '945623323', 'La Serna, 24', 'artuke@artuke.com', 'http://tiendakelo-kelotienda.rhcloud.com/32-large_default/vestido-estampado.jpg', '', '', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=artuke&submit_search='),
('https://www.mediafire.com/convkey/aa73/0b5185001sn6qv56g.jpg', 'La familia Berzal tiene desde tiempo inmemorial su explotación vitícola en esta villa.', 'La familia Berzal tiene desde tiempo inmemorial su explotación vitícola en esta villa. Actualmente la bodega conjuga modernidad \r\ncon tradición, elaborando vinos con la viticultura tradicional y las nuevas técnicas de elaboración.La bodega cuenta con sala \r\nde depósitos de acero inoxidable, una nave de barricas y una sala de cata.', 'Alava', 'Berzal', '945623368', 'Término Río Salado', 'info@dominioberzal.com', 'http://tiendakelo-kelotienda.rhcloud.com/44-large_default/dominio-berzal-tinto.jpg', '', 'http://tiendakelo-kelotienda.rhcloud.com/43-large_default/dominio-berzal-blanco.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=berzal&submit_search='),
('https://www.mediafire.com/convkey/4a35/7etb3z59zq5syxi6g.jpg', 'Luberri Monje Amestoy es una bodega alavesa de pura cepa. Sus diferentes viñedos orientados al mediodía y cuidados como un jardín, reposan entre la Sierra Cantabria, la de Toloño y el río Ebro.', 'Luberri Monje Amestoy es una bodega alavesa de pura cepa. Sus diferentes viñedos orientados al mediodía y cuidados como un jardín,reposan entre la Sierra Cantabria, la de Toloño y el río Ebro.', 'Alava', 'Luberri Monje Amestoy', '945606010', 'Camino de Los Rehoyos s/n', 'luberri@luberri.com', 'http://tiendakelo-kelotienda.rhcloud.com/50-large_default/luberri-tinto.jpg', '', 'http://tiendakelo-kelotienda.rhcloud.com/49-large_default/luberri-blanco.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=luberri&submit_search='),
('https://www.mediafire.com/convkey/955f/uzzzimtoozxl4jv6g.jpg', 'Nuestra bodega-museo está construida sobre seis calados subterráneos de piedra de sillería que datan de los siglos XV y XVI.', 'Cuando un vino conserva un nivel de fluctuaciones asimétricas netamente inferior al promedio, despuntan los viejos principios de la armonía que el pensamiento humano siempre identificó con la belleza. ', 'Alava', 'Valdelana', '945606055', 'Puente Barrihuelo, 67-69', 'enoturismo@bodegasvaldelana.com', 'http://tiendakelo-kelotienda.rhcloud.com/60-large_default/valdelana-tinto.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/59-large_default/valdelana-rosado.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/58-large_default/valdelana-blanco.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=valdelana&submit_search='),
('https://www.mediafire.com/convkey/656d/mdmcd6f828a962p6g.jpg', 'Viña Salceda se asienta donde las tierras de Elciego se unen a las orillas del Ebro, rodeada de su propio viñedo.', 'Cultivamos con auténtico mimo\r\nlas tres grandes variedades tintas de nuestra viticultura: el tempranillo, el graciano y el mazuelo, que es tanto como hablar\r\nde la gracia, el bouquet, el nervio y la fortaleza de nuestros vinos, que les permite alcanzar una longevidad envidiable.', 'Alava', 'Vina Salceda', '945606125', 'Carretera Cenicero, 3. km.', 'info@vinasalceda.com', 'http://tiendakelo-kelotienda.rhcloud.com/57-large_default/salceda-tinto.jpg', '', '', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=vina+salceda&submit_search='),
('https://www.mediafire.com/convkey/7f7b/5r7vfh42luat4h16g.jpg', 'Calados de hace más de 130 años y rodeada de viñedos. Uno de los escasos chateaux de la Rioja.', 'Calados de hace más de 130 años y rodeada de viñedos. Uno de los escasos chateaux de la Rioja. Un capricho del propietario (desgraciadamente fallecido hace unos años en accidente de tráfico). Se consolidará como un grande de Rioja.\r\n\r\nEn estos vinos se aúnan la tradición (maduros, bien evolucionados) y la modernidad (vivos de color y con vigor).', 'La Rioja', 'Amezola de la Mora', '941454532', 'Paraje Viña Vieja', 'info@bodegasamezola.es', 'http://tiendakelo-kelotienda.rhcloud.com/30-large_default/blusa.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/31-large_default/vestido-estampado.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/29-large_default/amezola-blanco.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=Amezola&submit_search='),
('https://www.mediafire.com/convkey/e982/5s7z7c7fp5udvmv6g.jpg', 'La nueva propiedad recogió el testigo de lo que fue la bodega familiar, cuya producción era casi artesanal.', 'La nueva propiedad recogió el testigo de lo que fue la bodega familiar, cuya producción era casi artesanal. En poco tiempo se \r\nacometieron inversiones, se modernizó todo el proceso de elaboración y embotellado, y se excavaron los impresionantes calados que \r\nen la actualidad tiene Antigua Usanza. La bodega está enclavada en una de las zonas más prestigiosas de la Rioja Alta, la cual \r\nreúne unas condiciones de privilegio para el cultivo de la viña.', 'La Rioja', 'Antigua Usanza', '941334156', '26338 - SAN VICENTE DE LA SONSIERRA', 'antiguausanza@antiguausanza.com', 'http://tiendakelo-kelotienda.rhcloud.com/42-large_default/bodega-antigua-usanza-tinto.jpg', '', 'http://tiendakelo-kelotienda.rhcloud.com/41-large_default/bodega-antigua-usanza-blanco.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=ANTIGUA+USANZA&submit_search='),
('https://www.mediafire.com/convkey/222d/7uee64appatb3b26g.jpg', 'Surge con un nuevo concepto del cooperativismo vitivinícola, con el objetivo de comercializar juntos sus vinos varios viticultores bajo una misma marca.', 'Surge con un nuevo concepto del cooperativismo vitivinícola, con el objetivo de comercializar juntos sus vinos varios viticultores bajo una misma marca. La elaboración se realiza en la bodega de cada socio y el proceso finaliza en la bodega central de Laguardia, que reúne las condiciones técnicas más avanzadas.', 'La Rioja', 'Artadi Cosecheros Alaveses', '945600119 ', 'Carretera de Logroño s/n ', 'comunicacion@artadi.com', 'http://tiendakelo-kelotienda.rhcloud.com/34-large_default/vestido-verano-estampado.jpg', '', 'http://tiendakelo-kelotienda.rhcloud.com/33-large_default/vestido-verano-estampado.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=artadi&submit_search='),
('https://www.mediafire.com/convkey/060b/qx6dpju9cmsf7f56g.jpg', 'Tiene el número de registro embotellador 10-LO, por lo que es la primera y más antigua firma embotelladora de la Denominación.', 'Tiene el número de registro embotellador 10-LO, por lo que es la primera y más antigua firma embotelladora de la Denominación. Lindante con la bodega está la finca Viña Pomal, coto adquirido y plantado por la sociedad en el año 1908. De sus vendiminas se elabora el vino Viña Pomal desde el año 1911. Dispone de más de 1.000 metros de calados de piedra de sillería. Hace poco (1997) ha sido adquirida por el grupo Codorniú.', 'La Rioja', 'Bilbainas', '941310147', 'Estación, 3 ', 'm.oyono@bodegasbilbainas.com', '', '', '', ''),
('https://www.mediafire.com/convkey/e756/7raglar8f7svfp36g.jpg', 'Apoyándose en un monasterio que data del siglo XVI, anteriormente castillo-fortaleza del conde de Eguía.', 'Apoyándose en un monasterio que data del siglo XVI, anteriormente castillo-fortaleza del conde de Eguía, un reducido número de profesionales del vino decidió establecer la bodega en 1982. Ls bodega, rodeada de viñedos, ha sido diseñada arqauitectónicamente para que armonice con el monasterio y está dotada de las más avanzadas técnicas de elaboración.', 'Navarra', 'Baron de Ley', '948694303', 'Ctra. De Mendavia-Lodosa, km. 5', 'info@barondeley.com', 'http://tiendakelo-kelotienda.rhcloud.com/39-large_default/baron-de-ley-tinto.jpg', '', 'http://tiendakelo-kelotienda.rhcloud.com/40-large_default/baron-de-ley-blanco.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=baron+de+ley&submit_search='),
('https://www.mediafire.com/convkey/bdc2/rzydnqm32u0uycr6g.jpg', 'Hablar de Vinícola Navarra es narrar la esencia histórica de Navarra.', 'Hablar de Vinícola Navarra es narrar la esencia histórica de Navarra. La bodega más antigua de la denominación —data de 1864— fue fundada por Julio Mihura y un grupo de socios franceses.', 'Navarra', 'Las Campanas', '948360131', 'Domecq Wines España, S.A.', 'info@domecqbodegas.com', 'http://tiendakelo-kelotienda.rhcloud.com/48-large_default/las-campanas-tinto.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/47-large_default/las-campanas-rosado.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/46-large_default/las-campanas-blanco.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=las+campanas&submit_search='),
('https://www.mediafire.com/convkey/e077/7vdsieeg1luoccc6g.jpg', 'La Bodega Nuestra Señora del Romero se gesto un 2 de Mayo de 1951 con la asistencia y refrenda en libro de Socios de 230.', 'La Bodega Nuestra Señora del Romero se gesto un 2 de Mayo de 1951 con la asistencia y refrenda en libro de Socios de 230. Oficialmente el día 25 de Septiembre de 1951, quedo constituida con 261 socios . En Mayo de 1952 se iniciaron las obras de la bodega para una capacidad de 2,5 millones de kilos , y cuatro meses más tarde, se recibió la primera cosecha de uva.', 'Navarra', 'Malon de echaide', '948851411', 'CP 31520 Cascante', ' info@malondeechaide.com', 'http://tiendakelo-kelotienda.rhcloud.com/53-large_default/malon-de-echaide-tinto.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/52-large_default/malon-de-echaide-rosado.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/51-large_default/malon-de-echaide-blanco.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=Malon+de+echaide&submit_search='),
('https://www.mediafire.com/convkey/fd28/x7xnmelken7jkv16g.jpg', 'Olite es la capital navarra del vino, antigua sede del viejo Reino, y nuestros caldos son reflejo de esta tierra de fuerte personalidad.', 'Olite es la capital navarra del vino, antigua sede del viejo Reino, y nuestros caldos son reflejo de esta tierra de fuerte personalidad. De hecho, el vino es un miembro más de nuestra familia.', 'Navarra', 'Ochoa', '948740006', 'C/Miranda de Arga 35\r\n31390 Olite', 'info@bodegasochoa.com', 'http://tiendakelo-kelotienda.rhcloud.com/24-large_default/ochoa-tinto.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/38-large_default/ochoa-rosado.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/35-large_default/ochoa-blanco.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=ochoa&submit_search='),
('https://www.mediafire.com/convkey/405b/z16bit48q6lv6q46g.jpg', 'Palacio de la Vega, la bodega navarra más laureada en el Challenge International du Vin por segundo año consecutivo.', 'Palacio de la Vega, la bodega navarra más laureada en el Challenge International du Vin por segundo año consecutivo.\r\n\r\nUno de los más prestigiosos y antiguos certámenes de vino internacional, el Challenge International du Vin, que se congrega anualmente en Blaye-Bourg (Burdeos) ha otorgado este año tres medallas de oro a Palacio de la Vega.', 'Navarra', 'Palacio de la Vega', '948527009', 'Condesa de la Vega, s/n\r\n31263 Dicastillo', 'infopalaciodelavega@palaciodelavega.es', 'http://tiendakelo-kelotienda.rhcloud.com/56-large_default/palacio-de-la-vega-tinto.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/55-large_default/palacio-de-la-vega-rosado.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/54-large_default/palacio-de-la-vega-blanco.jpg', 'http://tiendakelo-kelotienda.rhcloud.com/es/buscar?controller=search&orderby=position&orderway=desc&search_query=Palacio+de+la+Vega&submit_search=');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
